#!/usr/bin/env bash
../bin/bc -v -G arrays.bc
../bin/bc -v -G assignments.bc
../bin/bc -v -G character-literals.bc
../bin/bc -v -G compiler-variables.bc
../bin/bc -v -G composite-operators.bc
../bin/bc -v -G defer.bc
../bin/bc -v -G fibonacci.bc
../bin/bc -v -G for-arrays.bc
../bin/bc -v -G for-maps.bc
../bin/bc -v -G for-range.bc
../bin/bc -v -G generics.bc
../bin/bc -v -G inline-assembly.bc
../bin/bc -v -G lambda.bc
../bin/bc -v -G line-comments.bc
../bin/bc -v -G map.bc
../bin/bc -v -G pointers-with-member-access.bc
../bin/bc -v -G pointers.bc
../bin/bc -v -G relational-operators.bc
../bin/bc -v -G short.bc
../bin/bc -v -G simple.bc
../bin/bc -v -G stack-frames.bc
../bin/bc -v -G struct-literal.bc
../bin/bc -v -G tuple.bc
../bin/bc -v -G type-tagged-identifiers.bc
../bin/bc -v -G types.bc
../bin/bc -v -G while-loop.bc
../bin/bc -v -G with.bc
../bin/bc -v -G precedence.bc
